name: Upload source maps

on:
  push:
    branches:
      - test
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
            fetch-depth: 2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3

      - name: Set up Depot CLI
        uses: depot/setup-action@b0b1ea4f69e92ebf5dea3f8713a1b0c37b2126a5 # v1

      - name: Build and push container image
        id: build
        uses: depot/build-push-action@v1
        with:
            project: vgzrdx3nkk
            buildx-fallback: false
            push: false
            platforms: linux/arm64,linux/amd64
            build-args: COMMIT_HASH=${{ github.sha }}

