name: Upload source maps

on:
  push:
    branches:
      - test
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # Permissions to use OIDC token authentication
    permissions:
      contents: read
      id-token: write
      # Allows pushing to the GitHub Container Registry
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: depot/setup-action@v1
      - uses: depot/build-push-action@v1
        with:
          project: vgzrdx3nkk
          context: .

